import { useState } from 'react';
import { Database, Save, AlertCircle, CheckCircle, Eye, EyeOff } from 'lucide-react';
import { projectId, publicAnonKey } from '../utils/supabase/info';

interface SupabaseConfig {
  projectId: string;
  anonKey: string;
  serviceRoleKey: string;
}

export function SupabaseConfigScreen() {
  const [config, setConfig] = useState<SupabaseConfig>({
    projectId: '',
    anonKey: '',
    serviceRoleKey: ''
  });

  const [showServiceKey, setShowServiceKey] = useState(false);
  const [showCurrentKeys, setShowCurrentKeys] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState('');

  const handleSave = () => {
    // Validar que todos los campos estén llenos
    if (!config.projectId || !config.anonKey || !config.serviceRoleKey) {
      setError('Por favor completa todos los campos');
      return;
    }

    // Validar formato del projectId (debe ser alfanumérico)
    if (!/^[a-z0-9]+$/.test(config.projectId)) {
      setError('El Project ID debe contener solo letras minúsculas y números');
      return;
    }

    // Validar que las keys sean válidas (JWT antiguo o nuevo formato de Supabase)
    const isValidKey = (key: string) => {
      return key.startsWith('eyJ') || key.startsWith('sb_publishable_') || key.startsWith('sb_secret_');
    };

    if (!isValidKey(config.anonKey)) {
      setError('La Anon Public Key debe ser un JWT válido o empezar con "sb_publishable_"');
      return;
    }

    if (!isValidKey(config.serviceRoleKey)) {
      setError('La Service Role Key debe ser un JWT válido o empezar con "sb_secret_"');
      return;
    }

    setError('');

    // Mostrar instrucciones al usuario
    const fileContent = `/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "${config.projectId}"
export const publicAnonKey = "${config.anonKey}"`;

    const envContent = `SUPABASE_URL=https://${config.projectId}.supabase.co
SUPABASE_ANON_KEY=${config.anonKey}
SUPABASE_SERVICE_ROLE_KEY=${config.serviceRoleKey}
SUPABASE_DB_URL=postgresql://postgres.[PROJECT-ID]:[YOUR-PASSWORD]@aws-0-us-east-1.pooler.supabase.com:6543/postgres`;

    console.log('='.repeat(80));
    console.log('📝 CONFIGURACIÓN DE SUPABASE');
    console.log('='.repeat(80));
    console.log('\n1️⃣ ACTUALIZA EL ARCHIVO: /utils/supabase/info.tsx');
    console.log('-'.repeat(80));
    console.log(fileContent);
    console.log('\n2️⃣ CONFIGURA LAS VARIABLES DE ENTORNO EN SUPABASE');
    console.log('-'.repeat(80));
    console.log(envContent);
    console.log('\n' + '='.repeat(80));

    setSaved(true);
    
    // Mostrar por 5 segundos
    setTimeout(() => setSaved(false), 5000);
  };

  return (
    <div className="p-8 max-w-4xl mx-auto">
      {/* Header */}
      <div className="flex items-center gap-3 mb-8">
        <div className="bg-blue-100 p-3 rounded-lg">
          <Database className="w-8 h-8 text-blue-600" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Configuración de Supabase</h1>
          <p className="text-slate-600">Actualiza las credenciales de tu proyecto</p>
        </div>
      </div>

      {/* Credenciales Actuales */}
      <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-6">
        <h2 className="text-lg font-semibold text-green-900 mb-3">✅ Credenciales Actuales (en uso)</h2>
        <div className="space-y-3">
          <div>
            <p className="text-sm text-green-700 mb-1 font-medium">Project ID:</p>
            <p className="font-mono text-sm bg-white border border-green-200 rounded px-3 py-2 text-slate-800">
              {projectId}
            </p>
          </div>
          <div>
            <p className="text-sm text-green-700 mb-1 font-medium">Anon Public Key:</p>
            <div className="relative">
              <p className="font-mono text-sm bg-white border border-green-200 rounded px-3 py-2 text-slate-800 break-all">
                {showCurrentKeys ? publicAnonKey : '•'.repeat(60)}
              </p>
              <button
                onClick={() => setShowCurrentKeys(!showCurrentKeys)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
              >
                {showCurrentKeys ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
              </button>
            </div>
          </div>
          <div>
            <p className="text-sm text-green-700 mb-1 font-medium">URL del Proyecto:</p>
            <p className="font-mono text-sm bg-white border border-green-200 rounded px-3 py-2 text-slate-800">
              https://{projectId}.supabase.co
            </p>
          </div>
        </div>
      </div>

      {/* Instrucciones */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-6">
        <h2 className="text-lg font-semibold text-blue-900 mb-3">📋 Cómo obtener las credenciales</h2>
        <ol className="space-y-2 text-sm text-blue-800">
          <li className="flex gap-2">
            <span className="font-semibold">1.</span>
            <span>Ve a tu proyecto en Supabase: <code className="bg-blue-100 px-1 rounded">https://supabase.com/dashboard</code></span>
          </li>
          <li className="flex gap-2">
            <span className="font-semibold">2.</span>
            <span>En el menú lateral, haz clic en <strong>⚙️ Settings → API</strong></span>
          </li>
          <li className="flex gap-2">
            <span className="font-semibold">3.</span>
            <span>Copia el <strong>Project URL</strong> (extrae solo el ID, ej: si es "https://abc123xyz.supabase.co", copia "abc123xyz")</span>
          </li>
          <li className="flex gap-2">
            <span className="font-semibold">4.</span>
            <span>Copia la <strong>anon public</strong> key</span>
          </li>
          <li className="flex gap-2">
            <span className="font-semibold">5.</span>
            <span>Copia la <strong>service_role</strong> key (haz clic en "Reveal" primero) ⚠️ <strong>¡Nunca la compartas!</strong></span>
          </li>
        </ol>
      </div>

      {/* Formulario */}
      <div className="bg-white border border-slate-200 rounded-lg p-6 space-y-6">
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-2">
            Project ID *
          </label>
          <input
            type="text"
            value={config.projectId}
            onChange={(e) => setConfig({ ...config, projectId: e.target.value.toLowerCase().trim() })}
            placeholder="ej: abc123xyz"
            className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-sm"
          />
          <p className="text-xs text-slate-500 mt-1">
            Solo el ID, sin "https://" ni ".supabase.co"
          </p>
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-2">
            Anon Public Key *
          </label>
          <input
            type="text"
            value={config.anonKey}
            onChange={(e) => setConfig({ ...config, anonKey: e.target.value.trim() })}
            placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
            className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-sm"
          />
          <p className="text-xs text-slate-500 mt-1">
            Key pública - Segura para usar en el frontend
          </p>
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-2">
            Service Role Key * <span className="text-red-600 font-bold">⚠️ CONFIDENCIAL</span>
          </label>
          <div className="relative">
            <input
              type={showServiceKey ? "text" : "password"}
              value={config.serviceRoleKey}
              onChange={(e) => setConfig({ ...config, serviceRoleKey: e.target.value.trim() })}
              placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
              className="w-full px-4 py-2 pr-12 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-sm"
            />
            <button
              type="button"
              onClick={() => setShowServiceKey(!showServiceKey)}
              className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
            >
              {showServiceKey ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
            </button>
          </div>
          <p className="text-xs text-red-600 mt-1 font-medium">
            ⚠️ ¡NUNCA compartas esta key! Solo se usa en el servidor
          </p>
        </div>

        {/* Mensajes */}
        {error && (
          <div className="flex items-center gap-2 p-4 bg-red-50 border border-red-200 rounded-lg">
            <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0" />
            <p className="text-sm text-red-800">{error}</p>
          </div>
        )}

        {saved && (
          <div className="flex items-center gap-2 p-4 bg-green-50 border border-green-200 rounded-lg">
            <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0" />
            <p className="text-sm text-green-800">
              ✅ Configuración preparada. <strong>Revisa la consola del navegador</strong> para ver las instrucciones de actualizacin.
            </p>
          </div>
        )}

        {/* Botón */}
        <button
          onClick={handleSave}
          className="w-full flex items-center justify-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium"
        >
          <Save className="w-5 h-5" />
          Generar Configuración
        </button>
      </div>

      {/* Advertencia de seguridad */}
      <div className="mt-6 bg-yellow-50 border border-yellow-200 rounded-lg p-6">
        <div className="flex items-start gap-3">
          <AlertCircle className="w-6 h-6 text-yellow-600 flex-shrink-0 mt-0.5" />
          <div>
            <h3 className="font-semibold text-yellow-900 mb-2">🔒 Seguridad Importante</h3>
            <ul className="space-y-1 text-sm text-yellow-800">
              <li>• La <strong>Service Role Key</strong> tiene acceso completo a tu base de datos</li>
              <li>• Solo debe usarse en el servidor (Edge Functions), nunca en el frontend</li>
              <li>• No la compartas ni la subas a repositorios públicos</li>
              <li>• Si crees que se filtró, regenera las keys desde Supabase</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Siguiente paso */}
      <div className="mt-6 bg-slate-50 border border-slate-200 rounded-lg p-6">
        <h3 className="font-semibold text-slate-900 mb-3">📌 Siguiente Paso</h3>
        <p className="text-sm text-slate-700 mb-3">
          Después de actualizar las credenciales, necesitas:
        </p>
        <ol className="space-y-2 text-sm text-slate-700">
          <li className="flex gap-2">
            <span className="font-semibold">1.</span>
            <span>Guardar los cambios en los archivos</span>
          </li>
          <li className="flex gap-2">
            <span className="font-semibold">2.</span>
            <span>Recargar la aplicación (F5)</span>
          </li>
          <li className="flex gap-2">
            <span className="font-semibold">3.</span>
            <span>Ir a "Backend Admin" y hacer clic en <strong>"Migrar Datos"</strong></span>
          </li>
        </ol>
      </div>
    </div>
  );
}